name: "[DEV] deployment "
on: 
   push:
    branches: dev
    workflow_dispatch: {}

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: "Deploy to GIT"